# Generated by Django 4.1 on 2022-11-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_pin_code_order_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax_data',
            field=models.JSONField(blank=True, help_text="Data format: {'tax_type':{'tax_percentage':'tax_amount'}}", null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_tax',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
